# label rules used by .github/workflows/label.yml

api:
  - changed-files:
    - any-glob-to-any-file:
      - canarieapi/api.py
      - canarieapi/app_object.py
      - canarieapi/reverse_proxied.py
      - canarieapi/status.py
      - canarieapi/utility_rest.py
      - canarieapi/wsgi.py

config:
  - changed-files:
    - any-glob-to-any-file:
      - canarieapi/default_configuration.py
      - canarieapi/schema.py

monitor:
  - changed-files:
    - any-glob-to-any-file:
      - canarieapi/logparser.py
      - canarieapi/monitor.py

# label 'ci' all automation-related steps and files
ci:
  - changed-files:
    - any-glob-to-any-file:
      - .*  # all '.<>' files
      - .github/**/*
      - ci/**/*
      - hooks/**/*
      - Makefile
      - Dockerfile*
      - setup.cfg

doc:
  - changed-files:
    - any-glob-to-any-file:
      - "*.rst"
      - "*.example"
      - doc/**/*
      - requirements-doc.txt

db:
  - changed-files:
    - any-glob-to-any-file:
      - canarieapi/database_schema.sql

tests:
  - changed-files:
    - any-glob-to-any-file:
      - tests/**/*
      - requirements-dev.txt

ui:
  - changed-files:
    - any-glob-to-any-file:
      - canarieapi/static/*
      - canarieapi/templates/*
