services:
  canarie-api:
    build: .
    image: canarie-api # this will build a local image (change this to use one from a registry)
    ports:
      - '2000:2000'
    volumes:
      # share the sqlite database file between containers with this volume
      - data:/data/

  canarie-api-cron:
    build: .
    image: canarie-api # this will build a local image (change this to use one from a registry)
    command: cron -f
    depends_on:
      - canarie-api
    volumes:
      # The access_logs volume shares the nginx logs between the canarie-api-cron service and the proxy service
      # It is only required if the PARSE_LOGS setting is True.
      - access_logs:/logs/
      # share the sqlite database file between containers with this volume
      - data:/data/

  proxy:
    image: nginx
    volumes:
      # This nginx config file ensure that the nginx container will write the access logs to stdout as well as a file
      # on disk. This is required because canarie-api-cron expects a regular file to parse logs from.
      - ./nginx-log.conf:/etc/nginx/conf.d/nginx-log.conf
      - access_logs:/logs/

volumes:
  access_logs:
  data:
