x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: "10"

services:
  canarie-api:
    build: .
    image: canarie-api # this will build a local image (change this to use one from a registry)
    ports:
      - '2000:2000'
    volumes:
      - workdir:/opt/local/src/CanarieAPI/
    logging: *default-logging
  canarie-api-cron:
    build: .
    image: canarie-api # this will build a local image (change this to use one from a registry)
    command: cron -f
    depends_on:
      - canarie-api
    volumes:
      - access_log:/opt/local/src/access_file.log
      - workdir:/opt/local/src/CanarieAPI/

  proxy:
    image: nginx
    ports:
      - "8080:80"
    logging:
      options:
        max-size: "50m"
        max-file: "10"

volumes:
  access_log:
  workdir:
