services:
  canarie-api:
    build: .
    image: canarie-api # this will build a local image (change this to use one from a registry)
    ports:
      - '2000:2000'
    volumes:
      - workdir:/opt/local/src/CanarieAPI/

  canarie-api-cron:
    build: .
    image: canarie-api # this will build a local image (change this to use one from a registry)
    command: cron -f
    depends_on:
      - canarie-api
    volumes:
      - access_logs:/logs/
      - workdir:/opt/local/src/CanarieAPI/

  proxy:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx-log.conf:/etc/nginx/conf.d/nginx-log.conf
      - access_logs:/logs/

volumes:
  access_logs:
  workdir:
