services:
  canarie-api:
    build: .
    image: canarie-api # this will build a local image (change this to use one from a registry)
    ports:
      - '2000:2000'
    volumes:
      - workdir:/opt/local/src/CanarieAPI/

  canarie-api-cron:
    build: .
    image: canarie-api # this will build a local image (change this to use one from a registry)
    command: cron -f
    depends_on:
      - canarie-api
    volumes:
      - access_log:/opt/local/src/access_file.log
      - workdir:/opt/local/src/CanarieAPI/

  proxy:
    image: nginx
    volumes:
      - access_log:/var/log/nginx/access.log

volumes:
  access_log:
  workdir:
